openapi: 3.0.2
info:
  title: Account Transaction
  description: API to manage transactions
  version: 1.0.0
tags:
  - name: Transaction
    description: API to manage transactions
paths:
  /transaction/deposite:
    post:
      tags:
        - Transaction
      summary: register an account
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDto'
      responses:
        201:
          description: new account was registered
components:
  schemas:
    ErrorDto:
      type: object
      properties:
        code:
          type: integer
          format: int32
          description: Problem type code
        message:
          type: string
          description: A short, summary of the problem type
        uri:
          type: string
          format: uri
          description: An absolute URI that identifies the problem type
          default: 'about:blank'
        dateTime:
          type: string
          format: date-time
          nullable: false
          description: Error date (yyyy-MM-dd HH:mm:ss)